---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dotafoxr/public_html/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R app.js $DEPLOYPATH
    - /bin/cp -R tmp $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R package-lock.json $DEPLOYPATH
    - /bin/cp -R node_modules.txt $DEPLOYPATH
